version: '3'

services:
    isi-mongo:
        image: mongo
        container_name: isi-mongo
        restart: always
        volumes:
            - mongo:/data/db
        ports:
            - '27027:27017'

    isi-api:
        image: ewaight/isi-api
        container_name: isi-api
        environment:
            DATABASE_URI: 'mongodb://isi-mongo:27017/isi'
            PORT: 5000
        ports:
            - '3030:5000'
        restart: always
        depends_on:
            - isi-mongo

    isi-web:
        image: ewaight/isi-web
        container_name: isi-web
        ports:
            - '80:80'
        restart: always
        depends_on:
            - isi-api

volumes:
    mongo:
