version: '3'

services:
  isi-web:
    image: ewaight/isi-web
    container_name: isi-web
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - '80:80'
    restart: always
